import type { Metadata } from "next";
import "@/styles/globals.css";
import Providers from "@/app/_trpc/Providers";

export const metadata: Metadata = {
  title: "Next App with tRPC example",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
